<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_management_consultancy"
 *
 * Auto generated by Extension Builder 2019-07-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RKW Management Consultancy',
    'description' => 'Provides a form for mangement consultancy with a Backend Module for evaluation and csv export',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler',
    'author_email' => 'maximilian@faesslerweb.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'rkw_registration' => '8.7.0-8.7.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
